### ISSUE TITLE
ModuleNotFoundError: No module named 'scrapy.xlib'

### ISSUE THREAD

**Issue by Hytalecreed** [havanagrawal/GoodreadsScraper#5]
I am trying to scrape a Goodreads page listopia: 2438.REALLY_Underrated_Books_Fewer_than_1_000_Ratings

But when I am running this command or anyother commands I am getting an error
`scrapy crawl \
  --logfile=scrapy.log \
  -a start_page_no=1 \
  -a end_page_no=34 \
  -a list_name="2438.REALLY_Underrated_Books_Fewer_than_1_000_Ratings" \
  -s OUTPUT_FILE_SUFFIX="books_0_1000" \
  list`

This is log from scrapy.log

`2020-03-20 22:17:42 [scrapy.utils.log] INFO: Scrapy 2.0.1 started (bot: GoodreadsScraper)
2020-03-20 22:17:42 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 20.3.0, Python 3.6.9 (default, Nov  7 2019, 10:44:02) - [GCC 8.3.0], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Linux-5.3.0-42-generic-x86_64-with-elementary-5.1.2-hera
2020-03-20 22:17:42 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2020-03-20 22:17:42 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'GoodreadsScraper',
 'DOWNLOAD_DELAY': 1,
 'LOG_FILE': 'scrapy.log',
 'NEWSPIDER_MODULE': 'GoodreadsScraper.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['GoodreadsScraper.spiders']}
2020-03-20 22:17:42 [scrapy.extensions.telnet] INFO: Telnet Password: 9f9e3833e706dca6
2020-03-20 22:17:42 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2020-03-20 22:17:42 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-03-20 22:17:42 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-03-20 22:17:42 [twisted] CRITICAL: Unhandled error in Deferred:
2020-03-20 22:17:42 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/media/movp/Media/Scraping/Book Scraping/projectgr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/media/movp/Media/Scraping/Book Scraping/projectgr/lib/python3.6/site-packages/scrapy/crawler.py", line 89, in crawl
    self.engine = self._create_engine()
  File "/media/movp/Media/Scraping/Book Scraping/projectgr/lib/python3.6/site-packages/scrapy/crawler.py", line 103, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/media/movp/Media/Scraping/Book Scraping/projectgr/lib/python3.6/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/media/movp/Media/Scraping/Book Scraping/projectgr/lib/python3.6/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/media/movp/Media/Scraping/Book Scraping/projectgr/lib/python3.6/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/media/movp/Media/Scraping/Book Scraping/projectgr/lib/python3.6/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/media/movp/Media/Scraping/Book Scraping/projectgr/lib/python3.6/site-packages/scrapy/utils/misc.py", line 50, in load_object
    mod = import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/movp/Media/Scraping/Book Scraping/GoodreadsScraper-master/GoodreadsScraper/pipelines.py", line 9, in <module>
    from scrapy.xlib.pydispatch import dispatcher
ModuleNotFoundError: No module named 'scrapy.xlib'
`
I used a virtual env `projectgr` and not sure what is causing the error. I am new to python and scrapy, any help would be appreciated.

Thanks.

**Comment by havanagrawal** [comment]
Hello, I just pushed f6ee8836f09fdf857684a3a22395b23195172e0e which should resolve this issue, let me know if that fixes it :)
